const PERFIS = ["CLIENTE", "ATENDENTE", "COZINHA", "GERENTE", "ADMIN"];
const CANAIS_PEDIDO = ["APP", "TOTEM", "BALCAO", "PICKUP", "WEB"];
const STATUS_PEDIDO = [
  "AGUARDANDO_PAGAMENTO",
  "EM_PREPARO",
  "PRONTO",
  "ENTREGUE",
  "CANCELADO",
  "PAGAMENTO_RECUSADO"
];

const STATUS_PAGAMENTO = ["APROVADO", "RECUSADO"];
const TIPOS_ESTOQUE = ["ENTRADA", "SAIDA"];

module.exports = {
  PERFIS,
  CANAIS_PEDIDO,
  STATUS_PEDIDO,
  STATUS_PAGAMENTO,
  TIPOS_ESTOQUE
};

